### ISSUE TITLE
메인 랜딩 페이지에 우리가 만든 데모 시스템이 뭔지 알려줄 수 있으면 좋을듯

### ISSUE THREAD

**Issue by kmu-leeky** [kmu-bigdata/kmu-bigdata.github.io#4]
high-level 에서 설명해주는 거랑,
논문 링크 추가해주면 좋을것 같음.

**Comment by kde713** [comment]
랜딩을 별도로 분리할까요 아니면 `index.html` 상단에 추가할까요??

**Comment by kmu-leeky** [comment]
지금 첫페이지가 마음에 들어서. 현재 페이지 유지한채로 추가 정보를 보여주는게 좋을듯.

**Comment by kde713** [comment]
@kmu-leeky
[Commit 81c059d](https://github.com/kmu-bigdata/kmu-bigdata.github.io/commit/81c059dee61307aff6e2b2f785c95322b68f69d8) 확인 부탁드립니다.

**Comment by kmu-leeky** [comment]
Good job! 현재 버전에서 보면 아래 그래프가 가려지는데 (개인적으로 그래프가 좋아보이기에). 지금처럼 우측 상단에 X 표를 누르면 설명이 다 보이는것 보다는 Read More 버튼을 누르면 전체 설명이 보이게 하면 어떨까? (참조: http://stackoverflow.com/questions/33986023/html-how-to-make-a-read-more-button) 그러면 그래프도 안가려질테고. 설명 아래에 있는 Code on GitHub 버튼은  좋아보이고, 지금처럼 살려두며 좋을듯.

**Comment by kde713** [comment]
@kmu-leeky
demo용 신규 repository의 cdc2180 커밋 참조부탁드립니다

**Comment by kmu-leeky** [comment]
Good job
