### ISSUE TITLE
Deepspot cloud 프론트엔드 repo 분리의 필요성

### ISSUE THREAD

**Issue by kde713** [kmu-bigdata/kmu-bigdata.github.io#5]
### Summary
- Deepspot Cloud Front-end repository 분리의 필요성이 느껴짐

### Message
```
Deepspot Cloud 의 프론트엔드가 현재 Jekyll로 구성된 랩 사이트 내에 폴더로 종속되어 있어서 현재 유지보수를 할 때 난해함이 없지 않아 있습니다.
별도 서브도메인 할당이나 그런 부분이 가능하다면, deepspot cloud frontend를 별도 repository로 이관하여 관리하는게 어떨까요??
```

**Comment by kmu-leeky** [comment]
그렇지. 처음엔 랩 사이트 부터 만들려다 보니 그렇게 되었는데,
새로운 기능을 추가하고 관리하는데 어려움이 있다면 분리하지 않을 이유가 없을것 같아.
미팅때 얘기해보자.

**Comment by kde713** [comment]
@kmu-leeky 넵 알겠습니다~

**Comment by kde713** [comment]
@kmu-leeky 
랩 홈페이지 page generator를 Jekyll에서 jus로 변경해보는게 어떨까요?
Jekyll이 조금 더 유명하고 많이 쓰이긴 한데, jus가 좀 더 관리 측면과 코드 가독성 면에서 좀 더 좋아 보입니다.

*jus:* http://jus.js.org/
*kde713-testpage:* https://kde713.github.io/jus-test
*kde713-testrepo:* https://github.com/kde713/jus-test

**Comment by kmu-leeky** [comment]
사이트 디자인은 깔끔해 보인다.
현재 데모 사이트 cost-saving 까지 구현한 뒤에 사이트 분리하는걸 진행해보자.

**Comment by kmu-leeky** [comment]
good!
