### ISSUE TITLE
연구실 관리 서버에서 패스워드 기반 로그인 기능 없앨것

### ISSUE THREAD

**Issue by kmu-leeky** [kmu-bigdata/kmu-bigdata.github.io#59]
bd-1, bd-2, bd-3, gpu, p100 서버에서 패스워드 기반 로그인 방법을 없애고, ssh 키 기반의 로그인 방법만 활용하도록 설정.

@sungsu7437 @KimJeongChul @mjaysonnn 

RSA 기반 ssh 키를 만들어서 로그인에 활용하도록.

패스워드 기반 로그인 비활성화 - https://askubuntu.com/questions/435615/disable-password-authentication-in-ssh

ssh 키 기반 로그인 활성화 (각 계정에서 작업해야함) - https://www.digitalocean.com/community/tutorials/how-to-set-up-ssh-keys-on-ubuntu-1604

**Comment by KimJeongChul** [comment]
## Step 1 - Create the RSA Key Pair
로컬(맥북)에서 key pair를 확인한다.
$ ls ~/.ssh/
![image](https://user-images.githubusercontent.com/10591350/42149134-f4c62570-7e0f-11e8-943a-301cd44be713.png)
id_rsa와 id_rsa.pub이 없다면 Local에서 key pair 생성한다.

$ ssh-keygen
![image](https://user-images.githubusercontent.com/10591350/42149154-031a45f2-7e10-11e8-951c-1f7d9aecc213.png)

## Step 2 - Copy the Public Key to KMU-Bigdata Server
$ ssh-copy-id -p 52200 kimjc@203.246.113.16
![image](https://user-images.githubusercontent.com/10591350/42149160-081ce1fe-7e10-11e8-89b6-880950b5bb1a.png)

$ ssh-copy-id -p 52200 kimjc@203.246.113.17
$ ssh-copy-id -p 52200 kimjc@203.246.113.18
$ ssh-copy-id -p 52200 kimjc@203.246.113.19
$ ssh-copy-id -p 52200 kimjc@203.246.113.170

$ ssh kimjc@203.246.113.16 -p 52200
@sungsu7437 @mjaysonnn 
각 계정 작업 끝나면 비활성화 진행하겠습니다.

**Comment by sungsu7437** [comment]
작업 완료했습니다.

**Comment by KimJeongChul** [comment]
Step 3 - Disable Password Authentication on your Server
$ sudo vi /etc/ssh/sshd_config
PasswordAuthentication no
$ sudo systemctl restart ssh
![image](https://user-images.githubusercontent.com/10591350/42197854-d7121ad8-7ebf-11e8-9b1e-b73b4d298a82.png)
완료하였습니다.
