### ISSUE TITLE
웹 사이트 favicon 제작

### ISSUE THREAD

**Issue by kmu-leeky** [kmu-bigdata/kmu-bigdata.github.io#6]
랩 대표 로고와 favicon 만들어야 함

**Comment by mjaysonnn** [comment]
교수님 로고와 favicon에 kmu가 나와야 합니까?

**Comment by kmu-leeky** [comment]
지금 생각은 KMU BigData Lab 을 키워드로 만들었으면 하는데.. 가능하다면 전문적으로 하는 사람에게 맡기는 것도 좋을것 같기도 하고. 그리고 favicon 에는 그냥 작은 대표 이미지 하나만 들어가야 할듯.

**Comment by mjaysonnn** [comment]
아하 알겠슴다. 상징하고 싶은 이미지 있어야 하나요? 일러스트레이터 많이 써본 잘하는 인맥 대기중입니다.

**Comment by kmu-leeky** [comment]
좋다 ㅎㅎ 마음에 드는 이미지랑 문구를 같이 정해서 작업해보자.

**Comment by mjaysonnn** [comment]
넵넵 좋습니다!
