### ISSUE TITLE
빅데이터랩 전용 DNS 서버 구축 검토

### ISSUE THREAD

**Issue by kmu-leeky** [kmu-bigdata/kmu-bigdata.github.io#8]
현재 cs.kookmin.ac.kr 은 그리드 랩에서 관리되고 있으며,
빅데이터랩 별도의 도메인 관리 필요성이 증가하고 있음.

**Comment by mjaysonnn** [comment]
규연이형한테 한번 물어보겠습니다.

**Comment by kmu-leeky** [comment]
학교 정보 통신처에 확인필요
